name: Module Common CI
permissions:
  contents: read
on:
  workflow_call:

env:
  # Setting an environment variable with the value of a configuration variable
  PUBLISH_BRANCH: "refs/heads/main"
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  PACKAGE_NAME: "unknown"
  PACKAGE_VERSION: "unknown"
  NPM: "pnpm"
  NPM_VERSION: "unknown"
  HAVE_VALIDATE_SCRIPT: true
  HAVE_LINT_SCRIPT: true
  HAVE_UNIT_TEST_SCRIPT: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: dcarbone/install-jq-action@v2
      - uses: actions/checkout@v4

      - name: Identify project environment variables
        run: |
          echo "PACKAGE_NAME=$(cat package.json | jq -r .name)" | tee -a $GITHUB_ENV
          echo "PACKAGE_VERSION=$(cat package.json | jq -r .version)" | tee -a $GITHUB_ENV

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"

      - name: Get current npmjs version for ${{env.PACKAGE_NAME}}
        run: |
          echo "NPM_VERSION=$(curl -s https://registry.npmjs.org/${{ env.PACKAGE_NAME }} | jq -r '."dist-tags".latest')" | tee -a $GITHUB_ENV

      - name: Install workspace deps
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Validate
        if: env.HAVE_VALIDATE_SCRIPT == 'true'
        run: pnpm run validate

      - name: Test
        if: env.HAVE_UNIT_TEST_SCRIPT == 'true'
        run: pnpm test

      - name: Lint
        if: env.HAVE_LINT_SCRIPT == 'true'
        run: pnpm run lint

      - name: Publish ${{env.PACKAGE_NAME}} ${{env.PACKAGE_VERSION}}
        if: |
          github.ref == env.PUBLISH_BRANCH &&
          env.NPM_TOKEN != '' &&
          env.PACKAGE_VERSION != env.NPM_VERSION
        run: pnpm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
